 - name: create volume on host for nginx
   file: path=/var/docker_volumes/nginx/nginx/conf.d
         state=directory

 - name: template nginx.conf
   template: src=nginx.conf
             dest=/var/docker_volumes/nginx/nginx.conf
             mode=644
   notify:
     - reload nginx

 - name: pull Nginx image
   docker_pull: >
     repo={{ nginx_image }}

 - name: copy nginx.service
   template: >
     src=nginx.service
     dest=/usr/lib/systemd/system/nginx.service
   register: nginx_unit

 - name: systemctl daemon-reload
   command: /bin/systemctl daemon-reload
   when: nginx_unit.changed

 - name: enable and start nginx.service
   service: name=nginx
            enabled=yes
            state=started
