 - name: run nginx container
   docker: image={{ nginx_image }}
           name="nginx"
           ports="{{ advertise_ip }}:80:80"
           volumes="/some/nginx.conf:/etc/nginx.conf:ro"
           state=running
   register: nginx

 - set_fact:
     nginx_pid: "{{ nginx.ansible_facts.docker_containers[0].State.Pid }}"

 - name: copy nginx.conf
   sudo: yes
   template: src=nginx.conf
             dest=/etc/nginx.conf
             mode=644
   notify:
     - reload nginx
