---
 - name: install docker via yum
   yum: name=docker-io
        state=present

 - name: remove old docker binary
   # Note that the initial yum install is required to perform cgroups config
   file: path=/bin/docker
         state=absent

 - name: use latest docker binary
   # Note that the initial yum install is required to perform cgroups config
   get_url: url=https://get.docker.io/builds/Linux/x86_64/docker-latest
            dest=/bin/docker
            mode=0755

 - name: Template Docker service file for systemd
   # XXX: Overwritten when Docker is updated? Liable to break?
   # Also sets Docker args to enable Consul to act as DNS
   template: src=docker.service
             dest=/usr/lib/systemd/system/docker.service

 - name: enable and start docker
   service: name=docker
            enabled=yes
            state=started

 - name: install docker client
   pip: name=docker-py
        version=0.3.2
