---
 - name: create data directory for registry
   file: path=/var/docker_volumes/registry
         state=directory

 - name: install boto (s3 client)
   pip: name=boto
        version=2.30.0

 - name: GET Riak CS key from Consul
   uri: url=http://consul.service.consul:8500/v1/kv/riak_cs_key
        return_content=yes
   register: riak_cs_key

 - set_fact:
     riak_cs_key: "{{ riak_cs_key.json[0].Value | b64decode }}"

 - name: GET Riak CS secret in Consul
   uri: url=http://consul.service.consul:8500/v1/kv/riak_cs_secret
        return_content=yes
   register: riak_cs_secret

 - set_fact:
     riak_cs_secret: "{{ riak_cs_secret.json[0].Value | b64decode }}"

 - name: create registry bucket
   # Use the "fakes3" scheme to force Riak CS-compatible connection.
   s3: bucket=registry
       mode=create
       s3_url="fakes3://riak-cs.service.consul:8080"
       aws_access_key={{ riak_cs_key }}
       aws_secret_key={{ riak_cs_secret }}

 - name: run docker registry container with Riak CS as backend using S3 api
   docker: image={{ docker_reg_image }}
           name="docker-reg"
           ports={{ advertise_ip}}:5000:5000
           env="SETTINGS_FLAVOR=s3,AWS_BUCKET=registry,AWS_SECRET={{ riak_cs_secret }},AWS_KEY={{ riak_cs_key }},AWS_SECURE=False,BOTO_HOST=riak-cs.service.consul,BOTO_PORT=8080,BOTO_CALLING_FORMAT=boto.s3.connection.OrdinaryCallingFormat,STORAGE_PATH=/registry,GUNICORN_WORKERS=1,BOTO_DEBUG=2,SERVICE_NAME=registry"
           volumes="/var/docker_volumes/registry:/registry"
           state=running

 - name: template docker_registry_nginx.conf
   sudo: yes
   template: src=docker_registry_nginx.conf
             dest=/var/docker_volumes/nginx/nginx/conf.d/docker_registry_nginx.conf
             mode=644
   notify:
     - reload nginx
