---
 - name: create data directory for registry
   file:
     path: /var/docker_volumes/registry
     state: directory

 - name: set docker-reg environment vars in Consul
   uri:
     url: "http://consul-http.service.consul:8500/v1/kv/docker-reg/{{ item.key }}"
     method: PUT
     body: "{{ item.value}}"
   with_dict:
     SETTINGS_FLAVOR: local
     STORAGE_PATH: /registry
     GUNICORN_WORKERS: 1

 - name: pull docker registry image
   docker_pull:
     repo: "{{ docker_reg_image }}"

 - name: template docker-reg.service
   template:
     src: docker-reg.service
     dest: /usr/lib/systemd/system/docker-reg.service
   register: docker_reg_unit

 - name: systemctl daemon-reload
   command: /bin/systemctl daemon-reload
   when: docker_reg_unit.changed

 - name: enable and start docker-reg.service
   service:
     name: docker-reg
     enabled: yes
     state: started

 - name: template docker_registry_nginx.conf
   template:
     src: docker_registry_nginx.conf
     dest: /var/docker_volumes/nginx/nginx/conf.d/docker_registry.conf
     mode: 644
   notify:
     - reload nginx
