# Riak CS Object Storage - an S3-compatible object store
# https://registry.hub.docker.com/u/hectcastro/riak-cs/
#
# For testing, we use a cluster of size one.
# TODO: Use tagged image from private registry
# TODO: Disable ssh daemon since nsenter works just fine, thanks.
 - name: run Riak CS container
   docker: image="hectcastro/riak-cs"
           ports=5000:5000
           env="DOCKER_RIAK_CS_CLUSTER_SIZE=1"
           name="riak-cs01"
           publish_all_ports=True
           state=running
   register: riak_cs

 - set_fact:
     riak_cs_pid: "{{ riak_cs.ansible_facts.docker_containers[0].State.Pid }}"
     riak_cs_port: 8080
     riak_cs_ip:
       "{{ riak_cs.ansible_facts.docker_containers[0].
           NetworkSettings.IPAddress }}"

 - name: Extract Riak CS key
   shell: >
     sudo nsenter
     --target {{ riak_cs_pid }}
     --mount --uts --ipc --net --pid
     egrep "admin_key" /etc/riak-cs/app.config | cut -d'"' -f2
   register: riak_cs_key_reg

 - name: Extract Riak CS secret
   shell: >
     sudo nsenter
     --target {{ riak_cs_pid }}
     --mount --uts --ipc --net --pid
     egrep "admin_secret" /etc/riak-cs/app.config | cut -d'"' -f2
   register: riak_cs_secret_reg

 - set_fact:
     riak_cs_key: "{{ riak_cs_key_reg.stdout }}"
     riak_cs_secret: "{{ riak_cs_secret_reg.stdout }}"
