# Riak CS Object Storage - an S3-compatible object store
# https://registry.hub.docker.com/u/hectcastro/riak-cs/
#
# For testing, we use a cluster of size one.
#
# Port bindings:
# Riak HTTP API: 8098:8098
# Riak CS HTTP API: 8080:8080
#
# TODO: Use tagged image from private registry.
 - name: run Riak CS container
   docker: image="hectcastro/riak-cs"
           ports="{{ advertise_ip }}:8098:8098,{{ advertise_ip }}:8080:8080,SERVICE_8080_NAME=riak-cs""
           env="DOCKER_RIAK_CS_CLUSTER_SIZE=1"
           name="riak-cs"
           publish_all_ports=True
           state=running
   register: riak_cs

 - set_fact:
     riak_cs_pid: "{{ riak_cs.ansible_facts.docker_containers[0].State.Pid }}"


 - name: extract Riak CS key
 # Because this key is generated shortly after the first time the service
 # is initialized, we need to retry until it is generated.
   shell: >
     sudo nsenter
     --target {{ riak_cs_pid }}
     --mount --uts --ipc --net --pid
     egrep "admin_key" /etc/riak-cs/app.config | cut -d '"' -f2
   register: riak_cs_key
   until: riak_cs_key.stdout.find("admin-key") == -1
   retries: 10

 - name: extract Riak CS secret
   shell: >
     sudo nsenter
     --target {{ riak_cs_pid }}
     --mount --uts --ipc --net --pid
     egrep "admin_secret" /etc/riak-cs/app.config | cut -d'"' -f2
   register: riak_cs_secret

 - name: set Riak CS key in Consul
   uri: url=http://consul.service.consul:8500/v1/kv/riak_cs_key
        method=PUT
        body="{{ riak_cs_key.stdout }}"

 - name: set Riak CS secret in Consul
   uri: url=http://consul.service.consul:8500/v1/kv/riak_cs_secret
        method=PUT
        body="{{ riak_cs_secret.stdout }}"
