---
# Provision the droplet with:
# - Docker Engine
# - Riak CS (object store)
# - Docker Registry
- hosts: newdroplets
  user: root
  sudo: yes
  vars_files:
    - vars.yml
  roles:
    - common
    - docker_host
    - consul
    - docksul
    - riak_cs
    - docker_reg
