 - name: install ansible deps with yum
   yum:
     name: "{{ item }}"
     state: installed
   with_items:
    - git
    - gcc
    - python-devel

 - name: clone {{ ansible_repo }}
   git:
     repo: "{{ ansible_repo }}"
     dest: "/home/{{ admin_user }}/ansible"
   remote_user: "{{ admin_user }}"

 - name: install ansible deps with pip
   pip: name={{ item }}
   with_items:
    - paramiko
    - PyYAML
    - jinja2
    - dopy

 - name: put ansible on path in bashrc
   lineinfile:
     dest: "/home/{{ admin_user }}/.bashrc"
     line: source ~/ansible/hacking/env-setup > /dev/null
