# Docksul Docker-Consul bridge
# Automatically registers containers with published ports as Consul services.
# Uses the hosts network configuration.
 - name: run Docksul container
   docker: image="progrium/docksul"
           name="docksul"
           command="{{ advertise_ip }}:8500"
           net=host
           volumes="/var/run/docker.sock:/tmp/docker.sock"
           env="DOCKER_HOST=unix:///tmp/docker.sock"
           state=running

# Docker services will now auto-register and are queryable
# *from inside the containers* with, eg:
# dig consul-8500.service.consul. A
#
# or via HTTP:
# ETH0_IP=$(ip addr list eth0 | awk '/inet /{sub(/\/[0-9]+/,"",$2); print $2}')
# curl $ETH0_IP:8500/v1/agent/services
