# Docksul Docker-Consul bridge
# Automatically registers containers with published ports as Consul services.
 - name: pull Docksul image
   docker_pull: >
     repo={{ docksul_image }}

 - name: template docksul.service
   template: >
     src=docksul.service
     dest=/usr/lib/systemd/system/docksul.service
   register: docksul_unit

 - name: systemctl daemon-reload
   command: /bin/systemctl daemon-reload
   when: docksul_unit.changed

 - name: enable and start docksul.service
   service: name=docksul
            enabled=yes
            state=started

# Docker services will now auto-register and are queryable
# *from inside the containers* with, eg:
# dig consul-http.service.consul. A
#
# or via HTTP:
# ETH0_IP=$(ip addr list eth0 | awk '/inet /{sub(/\/[0-9]+/,"",$2); print $2}')
# curl $ETH0_IP:8500/v1/agent/services
