 - name: install pip with yum
   yum: name=python-pip
        state=installed

 - name: install httplib2 for ansible uri module
   pip: name=httplib2
        version=0.9

 - name: install passlib for ansible htpasswd module
   yum: name=python-passlib
        state=installed
